server:
  port: 9201
spring:
  application:
    name: linkwin-storage
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        register-enabled: true
        watch-delay: 1000
    sentinel:
      transport:
        dashboard: 127.0.0.1:8849
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 500
        readTimeout: 5000
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always